/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class by_quantumquartet_quanthink_mathCPlusPlus_NativeMathLib */

#ifndef _Included_by_quantumquartet_quanthink_mathCPlusPlus_NativeMathLib
#define _Included_by_quantumquartet_quanthink_mathCPlusPlus_NativeMathLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     by_quantumquartet_quanthink_mathCPlusPlus_NativeMathLib
 * Method:    solveExpressionC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_by_quantumquartet_quanthink_mathCPlusPlus_NativeMathLib_solveExpressionC
  (JNIEnv *, jobject, jstring);
#ifdef __cplusplus
}
#endif
#endif
